sudo: required

services:
    - docker

matrix:
    fast_finish: true
    include:
        - env: DOCK=1 IMAGE=bionic PY=2 RUN=unit
          python: 2.7
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=bionic PY=3 RUN=unit COVERALLS=1
          python: 3.5
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=bionic PY=3 RUN=style
          python: 3.5
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=fedora28 PY=2 RUN=unit
          python: 2.7
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=fedora28 PY=3 RUN=unit
          python: 3.5
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=archlinux PY=2 RUN=unit
          python: 2.7
          os: linux
          dist: trusty

        - env: DOCK=1 IMAGE=archlinux PY=3 RUN=unit
          python: 3.5
          os: linux
          dist: trusty

        - language: generic
          env: RUN=unit PY=2 HOMEBREW_NO_AUTO_UPDATE=1
          os: osx

        - language: generic
          env: RUN=unit PY=3 HOMEBREW_NO_AUTO_UPDATE=1
          os: osx


before_install:
    - echo PATH=$PATH;
    - ./ci/osx_fix_cellar.sh
    - ./ci/osx_fix_rvm.sh
    - ./ci/github_checkout_branch.sh

install:
    - ./ci/osx_get_py3.sh
    - ./ci/osx_get_pipvirtualenv.sh
    - ./ci/docker_build.sh

script:
    - ./ci/osx_run_tests.sh

    # run containers from images
    - if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ -v DOCK ]; then
          if [ "$PY" == "2" ] && [ "$RUN" == "unit" ]; then
              docker run
                  --interactive
                  --tty
                  plyer:py2;

          elif [ "$PY" == "3" ] && [ "$RUN" == "unit" ]; then
              if [ "${COVERALLS}" == "1" ]; then
                  docker run
                      --interactive
                      --tty
                      --env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
                      --env COVERALLS_SERVICE_NAME=travis-ci
                      --env TRAVIS_JOB_ID=$TRAVIS_JOB_ID
                      --env TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
                      --env PLYER_DEPLOY=${PLYER_DEPLOY:-"0"}
                      --env TWINE_REPOSITORY=$TWINE_REPOSITORY
                      --env TWINE_REPOSITORY_URL=$TWINE_REPOSITORY_URL
                      --env TWINE_USERNAME=$TWINE_USERNAME
                      --env TWINE_PASSWORD=$TWINE_PASSWORD
                      plyer:py3;

              else
                  docker run
                      --interactive
                      --tty
                      plyer:py3;
              fi;

          elif [ "$PY" == "3" ] && [ "$RUN" == "style" ]; then
              docker run
                  --interactive
                  --tty
                  plyer:style;
          fi;
        fi;
